TYPO3:
  Flow:
    object:
      excludeClasses:
       'zircote.hal' : ['.*']
    reflection:
      ignoredTags: ['api', 'package', 'subpackage', 'license', 'copyright', 'author', 'const', 'see', 'todo', 'scope', 'fixme', 'test', 'expectedException', 'depends', 'dataProvider', 'group', 'codeCoverageIgnore', 'rel', 'covers']

#Wwwision:
#  Hal:
#    browser:
#      defaultRequestHeaders:
#        'Some-Header': 'Some Value'